export type Vehicle = { id: string; brand: string; model: string; year: number };
export type User = { id: string; username: string; role: "admin" | "reader"; active: boolean };
export type Session = { access_token: string; token_type: "bearer"; user: User };
export type Job = { id: string; status: "queued" | "parsing" | "embedding" | "succeeded" | "failed"; error: string | null; attempts: number };
export type ManualVersion = { id: string; sha256: string; page_count: number; chunk_count: number; created_at: string; job: Job | null };
export type Manual = { id: string; vehicle_id: string; title: string; source: string; enabled: boolean; active_version_id: string | null; versions: ManualVersion[] };
export type Citation = { manual_id?: string; version_id?: string; manual_title: string; chapter_title: string; page_number: number; excerpt: string };
export type ChatResponse = { answer: string; steps: string[]; warnings: string[]; citations: Citation[]; grounded: boolean };
export type ChatRequest = { vehicle_id: string; question: string; chapter_titles?: string[] };
